### ISSUE TITLE
App Crash after payment process

### ISSUE THREAD

**Issue by dinak1989** [citruspay/plug-play-sdk-android#14]
Hi Team,

Im getting crash in CitrusUi activity.Kindly check it

java.lang.RuntimeException: Unable to resume activity {new.android.ui/com.citruspay.sdkui.ui.activities.CitrusUIActivity}: java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                                          at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
                                                                          at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:816)
                                                                          at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
                                                                          at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
                                                                          at com.citruspay.sdkui.ui.activities.a.onBackPressed(Unknown Source)
                                                                          at com.citruspay.sdkui.ui.activities.CitrusUIActivity.a(Unknown Source)
                                                                          at com.citruspay.sdkui.ui.activities.CitrusUIActivity.a(Unknown Source)
                                                                          at com.citruspay.sdkui.ui.b.a.onResume(Unknown Source)
                                                                          at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                          at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
                                                                          at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
                                                                          at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
                                                                          at com.citruspay.sdkui.ui.activities.CitrusUIActivity.onResumeFragments(Unknown Source)
                                                                          at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
                                                                          at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
                                                                          at android.app.Activity.performResume(Activity.java:5323)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
09-27 17:22:48.626 1607-1756/system_process W/ActivityManager:   Force finishing activity ticketnew.android.ui/com.citruspay.sdkui.ui.activities.CitrusUIActivity

**Comment by shiprasinghal1** [comment]
Hey , did u able to resolve it ?

**Comment by amol-d** [comment]
Any update on this?
